In [153]:
import pandas as pd

DATE = "19-05-2026" # DD-MM-YYYY format, modify to load dataframes from a different date

euro_dir = "../../Output/Paper_Testing/Euro_"
pga_dir = "../../Output/Paper_Testing/PGA_"
euro_path = euro_dir + DATE + ".xlsx"
pga_path = pga_dir + DATE + ".xlsx"

euro_winner = pd.read_excel(euro_path, sheet_name="Winner_Market")
euro_top5 = pd.read_excel(euro_path, sheet_name="Top5_Market")
euro_top10 = pd.read_excel(euro_path, sheet_name="Top10_Market")
euro_top20 = pd.read_excel(euro_path, sheet_name="Top20_Market")

pga_winner = pd.read_excel(pga_path, sheet_name="Winner_Market")
pga_top5 = pd.read_excel(pga_path, sheet_name="Top5_Market")
pga_top10 = pd.read_excel(pga_path, sheet_name="Top10_Market")
pga_top20 = pd.read_excel(pga_path, sheet_name="Top20_Market")

print(euro_winner.info())

<class 'pandas.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Surname                 155 non-null    str
 1   Firstname               155 non-null    str
 2   Rating                  155 non-null    float64
 3   Market_Odds             155 non-null    int64
 4   Model_Score             155 non-null    float64
 5   Probability             155 non-null    float64
 6   Normalised_Probability  155 non-null    float64
 7   Normalised_Model_Odds   155 non-null    float64
 8   Wed 6pm Odds            155 non-null    int64
 9   Min_Odds                155 non-null    int64
 10  Max_Odds                155 non-null    float64
 11  Bet                     93 non-null     str
 12  Stake                   93 non-null     float64
 13  Position                155 non-null    int64
 14  Profit                  93 non-null     float64
 15  Unnamed: 15             0 non-null      float64
 16  Unnamed: 16             0 non-null      float64
 17  Profit:                 0 non-null      float64
 18  BACK                    0 non-null      float64
 19  -130                    0 non-null      float64
 20  LAY                     0 non-null      float64
 21  642.48                  0 non-null      float64
 22  Unnamed: 22             0 non-null      float64
 23  Unnamed: 23             0 non-null      float64
 24  Criteria:               0 non-null      float64
 25  BACK.1                  0 non-null      float64
 26  65                      0 non-null      float64
 27  LAY.1                   0 non-null      float64
 28  1000                    0 non-null      float64
dtypes: float64(22), int64(4), str(3)
memory usage: 35.2 KB
None

In [154]:
def get_market_profits(df, market):
    back_profit =  df.columns[19]
    FL_lay_profit = df.columns[21]
    print(market, "Back profit:", back_profit)
    print(market, "Fixed liability lay profit:", FL_lay_profit)
    return back_profit, FL_lay_profit

euro_winner_existing_profits = get_market_profits(euro_winner, "Winner")
euro_top5_existing_profits = get_market_profits(euro_top5, "Top 5")
euro_top10_existing_profits = get_market_profits(euro_top10, "Top 10")
euro_top20_existing_profits = get_market_profits(euro_top20, "Top 20")

pga_winner_existing_profits = get_market_profits(pga_winner, "Winner")
pga_top5_existing_profits = get_market_profits(pga_top5, "Top 5")
pga_top10_existing_profits = get_market_profits(pga_top10, "Top 10")
pga_top20_existing_profits = get_market_profits(pga_top20, "Top 20")

for tour, markets in data.items():

Winner Back profit: -130
Winner Fixed liability lay profit: 642.48
Top 5 Back profit: 571.33
Top 5 Fixed liability lay profit: 90.96
Top 10 Back profit: -30
Top 10 Fixed liability lay profit: -148.43
Top 20 Back profit: 62.8
Top 20 Fixed liability lay profit: -40.08
Winner Back profit: -20
Winner Fixed liability lay profit: 88.51
Top 5 Back profit: -140
Top 5 Fixed liability lay profit: 56.23
Top 10 Back profit: -140
Top 10 Fixed liability lay profit: -70.48
Top 20 Back profit: -125.9
Top 20 Fixed liability lay profit: -239.14

In [155]:
def calculate_fixed_stake(df, max_liability, market):
    fixed_stake = round(max_liability / max(df['Normalised_Model_Odds']), 2)
    print(market, "fixed stake:", fixed_stake)
    return fixed_stake

euro_winner_FS = calculate_fixed_stake(euro_winner, 1000, "Winner")
euro_top5_FS = calculate_fixed_stake(euro_top5, 200, "Top 5")
euro_top10_FS = calculate_fixed_stake(euro_top10, 100, "Top 10")
euro_top20_FS = calculate_fixed_stake(euro_top20, 50, "Top 20")

pga_winner_FS = calculate_fixed_stake(pga_winner, 1000, "Winner")
pga_top5_FS = calculate_fixed_stake(pga_top5, 200, "Top 5")
pga_top10_FS = calculate_fixed_stake(pga_top10, 100, "Top 10")
pga_top20_FS = calculate_fixed_stake(pga_top20, 50, "Top 20")

Winner fixed stake: 1.43
Top 5 fixed stake: 1.52
Top 10 fixed stake: 1.27
Top 20 fixed stake: 1.31
Winner fixed stake: 2.01
Top 5 fixed stake: 1.38
Top 10 fixed stake: 0.97
Top 20 fixed stake: 0.96

In [163]:
def calculate_market_profits(df, market, stake_amount):
    df = df[df['Bet'] == 'LAY']
    US_profit = round(sum(df['Profit'] / df['Stake']), 2)
    FS_profit = round(sum((df['Profit'] / df['Stake']) * stake_amount), 2)
    print(market, "uniform stake profit:", US_profit)
    print(market, "fixed stake profit:", FS_profit)
    return US_profit, FS_profit

euro_winner_profits = calculate_market_profits(euro_winner, "Winner", euro_winner_FS)
euro_top5_profits = calculate_market_profits(euro_top5, "Top5", euro_top5_FS)
euro_top10_profits =  calculate_market_profits(euro_top10, "Top10", euro_top10_FS)
euro_top20_profits = calculate_market_profits(euro_top20, "Top20", euro_top20_FS)

pga_winner_profits = calculate_market_profits(pga_winner, "Winner", pga_winner_FS)
pga_top5_profits = calculate_market_profits(pga_top5, "Top5", pga_top5_FS)
pga_top10_profits =  calculate_market_profits(pga_top10, "Top10", pga_top10_FS)
pga_top20_profits = calculate_market_profits(pga_top20, "Top20", pga_top20_FS)

Winner uniform stake profit: 80.0
Winner fixed stake profit: 114.4
Top5 uniform stake profit: 16.0
Top5 fixed stake profit: 24.32
Top10 uniform stake profit: -13.14
Top10 fixed stake profit: -16.69
Top20 uniform stake profit: 19.19
Top20 fixed stake profit: 25.14
Winner uniform stake profit: 22.0
Winner fixed stake profit: 44.22
Top5 uniform stake profit: 36.5
Top5 fixed stake profit: 50.37
Top10 uniform stake profit: 10.48
Top10 fixed stake profit: 10.17
Top20 uniform stake profit: -15.23
Top20 fixed stake profit: -14.62

In [157]:
euro_data = {
    "Market" : ["Winner", "Top 5", "Top 10", "Top 20", "Total"],
    "Back Profit": [euro_winner_existing_profits[0], euro_top5_existing_profits[0], euro_top10_existing_profits[0], euro_top20_existing_profits[0], sum([euro_winner_existing_profits[0], euro_top5_existing_profits[0], euro_top10_existing_profits[0], euro_top20_existing_profits[0]])],
    "FL Lay Profit": [euro_winner_existing_profits[1], euro_top5_existing_profits[1], euro_top10_existing_profits[1], euro_top20_existing_profits[1], sum([euro_winner_existing_profits[1], euro_top5_existing_profits[1], euro_top10_existing_profits[1], euro_top20_existing_profits[1]])],
    "£1 US Lay Profit": [euro_winner_profits[0], euro_top5_profits[0], euro_top10_profits[0], euro_top20_profits[0], sum([euro_winner_profits[0], euro_top5_profits[0], euro_top10_profits[0], euro_top20_profits[0]])],
    "FS Lay Profit": [euro_winner_profits[1], euro_top5_profits[1], euro_top10_profits[1], euro_top20_profits[1], sum([euro_winner_profits[1], euro_top5_profits[1], euro_top10_profits[1], euro_top20_profits[1]])],

}

euro_df = pd.DataFrame(euro_data)
display(euro_df)

pga_data = {
    "Market" : ["Winner", "Top 5", "Top 10", "Top 20", "Total"],
    "Back Profit": [pga_winner_existing_profits[0], pga_top5_existing_profits[0], pga_top10_existing_profits[0], pga_top20_existing_profits[0], sum([pga_winner_existing_profits[0], pga_top5_existing_profits[0], pga_top10_existing_profits[0], pga_top20_existing_profits[0]])],
    "FL Lay Profit": [pga_winner_existing_profits[1], pga_top5_existing_profits[1], pga_top10_existing_profits[1], pga_top20_existing_profits[1], sum([pga_winner_existing_profits[1], pga_top5_existing_profits[1], pga_top10_existing_profits[1], pga_top20_existing_profits[1]])],
    "£1 US Lay Profit": [pga_winner_profits[0], pga_top5_profits[0], pga_top10_profits[0], pga_top20_profits[0], sum([pga_winner_profits[0], pga_top5_profits[0], pga_top10_profits[0], pga_top20_profits[0]])],
    "FS Lay Profit": [pga_winner_profits[1], pga_top5_profits[1], pga_top10_profits[1], pga_top20_profits[1], sum([pga_winner_profits[1], pga_top5_profits[1], pga_top10_profits[1], pga_top20_profits[1]])],

}

pga_df = pd.DataFrame(pga_data)
display(pga_df)

   Market  Back Profit  FL Lay Profit  £1 US Lay Profit  FS Lay Profit
0  Winner      -130.00         642.48             80.00         114.40
1   Top 5       571.33          90.96             16.00          24.32
2  Top 10       -30.00        -148.43            -13.14         -16.69
3  Top 20        62.80         -40.08             19.19          25.14
4   Total       474.13         544.93            102.05         147.17

   Market  Back Profit  FL Lay Profit  £1 US Lay Profit  FS Lay Profit
0  Winner        -20.0          88.51             22.00          44.22
1   Top 5       -140.0          56.23             36.50          50.37
2  Top 10       -140.0         -70.48             10.48          10.15
3  Top 20       -125.9        -239.14            -15.23         -14.60
4   Total       -425.9        -164.88             53.75          90.14